# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          su
          wget https://github.com/curl/curl/releases/download/curl-7_55_0/curl-7.55.0.tar.gz
          ./configure
          make 
          make install
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(pkgdir = "./chigcrim", dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(path = "./chigcrim", args = "--no-manual", error_on = "error")
        shell: Rscript {0}
